# Generated by Django 3.0.4 on 2020-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttoken',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
