# Generated by Django 3.0.4 on 2020-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0004_projecttoken_lastaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttoken',
            old_name='lastAction',
            new_name='last_action',
        ),
    ]
