# Generated by Django 3.0.4 on 2020-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0006_auto_20201104_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='c_index',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
