# Generated by Django 3.0.4 on 2021-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0008_auto_20210511_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plot',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
