# Generated by Django 3.0.4 on 2021-05-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0009_project_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='plot',
        ),
        migrations.AlterField(
            model_name='coxplot',
            name='file',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
