# Generated by Django 3.0.4 on 2021-05-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0010_auto_20210517_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoxPlot',
        ),
    ]
