# Generated by Django 3.0.4 on 2021-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0013_auto_20210517_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='coxplot',
            name='interactive',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
