# Generated by Django 3.0.4 on 2021-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0014_coxplot_interactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcensorshipplot',
            name='table',
        ),
        migrations.RemoveField(
            model_name='kmplot',
            name='table',
        ),
        migrations.RemoveField(
            model_name='naplot',
            name='table',
        ),
        migrations.AddField(
            model_name='project',
            name='plot',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.DeleteModel(
            name='CoxPlot',
        ),
        migrations.DeleteModel(
            name='EventCensorshipPlot',
        ),
        migrations.DeleteModel(
            name='KMPlot',
        ),
        migrations.DeleteModel(
            name='NAPlot',
        ),
    ]
