# Generated by Django 3.0.4 on 2021-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0016_resulttable_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulttable',
            old_name='plot',
            new_name='plot_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plot',
        ),
        migrations.AddField(
            model_name='resulttable',
            name='plot_layout',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
