# Generated by Django 3.0.4 on 2021-05-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0017_auto_20210517_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulttable',
            old_name='plot_data',
            new_name='plot',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='plot_layout',
        ),
    ]
