# Generated by Django 3.0.4 on 2021-05-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0020_auto_20210520_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='errorMessage',
            new_name='error_message',
        ),
    ]
