# Generated by Django 3.0.4 on 2021-07-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0023_auto_20210715_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='penalization',
            new_name='penalizer',
        ),
    ]
