# Generated by Django 3.2.5 on 2021-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0024_auto_20210715_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='method',
            field=models.CharField(choices=[('unviariate', 'Categorical Analysis'), ('cox', 'Cox proportional hazards model'), ('rsf', 'Random Survival Forest')], default='univariate', max_length=255),
        ),
    ]
