# Generated by Django 3.2.5 on 2021-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0025_auto_20210720_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='method',
            field=models.CharField(choices=[('unviariate', 'Univariate analysis'), ('cox', 'Cox proportional hazards model'), ('rsf', 'Random Survival Forest')], default='univariate', max_length=255),
        ),
    ]
