# Generated by Django 3.2.5 on 2021-07-20 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0026_alter_project_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_depth',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='min_samples_leaf',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='project',
            name='min_samples_split',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='project',
            name='n_estimators',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
