# Generated by Django 3.2.5 on 2021-07-26 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0028_auto_20210721_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_depth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
