# Generated by Django 3.2.5 on 2021-09-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0031_project_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model',
        ),
    ]
