# Generated by Django 3.2.5 on 2021-11-25 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0032_remove_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_time',
            field=models.FloatField(default=53.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='min_time',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='step_size',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
