# Generated by Django 4.0 on 2022-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0034_auto_20211125_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='iter_state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
