# Generated by Django 4.0 on 2022-01-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0035_project_iter_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='iter_state',
        ),
    ]
