# Generated by Django 4.0 on 2022-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0036_remove_project_iter_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='max_depth',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_samples_leaf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_samples_split',
        ),
        migrations.RemoveField(
            model_name='project',
            name='oob',
        ),
        migrations.RemoveField(
            model_name='project',
            name='test_sample_number',
        ),
        migrations.AddField(
            model_name='project',
            name='internal_state',
            field=models.CharField(default='init', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_sites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='smpc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='from_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_iters',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='method',
            field=models.CharField(choices=[('unviariate', 'Univariate analysis'), ('cox', 'Cox proportional hazards model')], default='univariate', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_time',
            field=models.FloatField(default=100),
        ),
    ]
