# Generated by Django 4.0 on 2022-01-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0037_remove_project_max_depth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='n_estimators',
        ),
    ]
