# Generated by Django 5.0.7 on 2024-07-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_algo', '0039_alter_project_privacy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='smpc',
            field=models.BooleanField(default=True),
        ),
    ]
