name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Blitzhub
        uses: docker/login-action@v1
        with:
          registry: registry.blitzhub.io
          username: ${{ secrets.BLITZHUB_USERNAME }}
          password: ${{ secrets.BLITZHUB_PW }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          image: partea_server
          registry: registry.blitzhub.io
          tags: prod
          secrets: |
            "SECRET_KEY=${{ secrets.SECRET_KEY }}"
          context: "{{defaultContext}}"